name = "remixflare-starter"
main = "./dist/index.js"
compatibility_date = "2024-08-27"

legacy_assets = "public"

[define]
"process.env.REMIX_DEV_ORIGIN"= "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT"= "8002"
